#!/bin/bash

sudo apt update
sudo apt install software-properties-common -y
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible git -y

TMPDIR=$(mktemp -d)
git clone https://github.com/becker/ansible-local-dev.git $TMPDIR

ansible-playbook --connection=local $TMPDIR/bootstrap.yml

rm -rf $TMPDIR