#!/bin/bash

sudo apt update
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible git -y


git clone https://github.com/becker/ansible-local-dev.git .

cd local-bootstrap/
ansible-playbook --connection=local bootstrap.yml