- name: Add neovim repository
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'

- name: Add fish repository
  apt_repository:
    repo: 'ppa:fish-shell/release-3'

- name: Add nginx repository
  apt_repository: 
    repo: 'ppa:nginx/stable'
    
- name: Install packages
  apt: 
    install_recommends: no
    name: "{{ item }}"
    with_items:
    - build-essential
    - curl
    - file
    - git
    - git-flow
    - neovim
    - fish
    - nginx